### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by smoil-ali** [Javernaut/ffmpeg-android-maker#46] opened 2021-01-03 17:11 UTC
java.lang.UnsatisfiedLinkError: dlopen failed: library "libswresample.so" not found
![file_not_found](https://user-images.githubusercontent.com/40652937/103484418-8c95c180-4e10-11eb-81a0-204579ea416d.png)

**Comment by Javernaut** [comment] 2021-01-03 17:37
Is a duplicate of [another issue](https://github.com/Javernaut/WhatTheCodec/issues/8).

**Closed by Javernaut** 2021-01-03 17:37 UTC
